name = "SpectralParams"
uuid = "7801582f-3aad-4606-908d-7bb06f43e91d"
authors = ["Z.M. Vig"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
